include:
  - contributing.md
permalink: pretty
collections:
  algsets:
    permalink: /algs/:name
    output: true
defaults:
  -
    scope:
      path: ""
      type: "algsets"
    values:
      layout: "algset"
plugins:
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-titles-from-headings
title: ZZ method
tagline: A website about the ZZ method.
description: A website about the ZZ method.
remote_theme: chrisrhymes/bulma-clean-theme